## Importing libraries

In [32]:
import pandas as pd
import numpy as np

## Loading data

In [33]:
df = pd.read_csv('Messy_Employee_dataset.csv', encoding='utf-8', sep=',')

## Initial inspection

In [34]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

In [36]:
df.describe(include='all')

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
count,1020,1020,1020,809.000000,1020,1020,1020,996.000000,1020,1.020000e+03,1020,1020
unique,1020,8,8,NaN,36,3,760,NaN,64,NaN,4,2
top,EMP1000,Frank,Brown,NaN,HR-Florida,Pending,6/10/2024,NaN,grace.brown@example.com,NaN,Good,True
freq,1,142,148,NaN,41,356,5,NaN,27,NaN,270,513
mean,NaN,NaN,NaN,32.484549,NaN,NaN,NaN,85155.056396,NaN,-4.942253e+09,NaN,NaN
std,NaN,NaN,NaN,5.656860,NaN,NaN,NaN,19873.727918,NaN,2.817326e+09,NaN,NaN
min,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,50047.320000,NaN,-9.994973e+09,NaN,NaN
25%,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,68392.487500,NaN,-7.341992e+09,NaN,NaN
50%,NaN,NaN,NaN,30.000000,NaN,NaN,NaN,85547.870000,NaN,-4.943997e+09,NaN,NaN
75%,NaN,NaN,NaN,40.000000,NaN,NaN,NaN,100974.027500,NaN,-2.520391e+09,NaN,NaN
max,NaN,NaN,NaN,40.000000,NaN,NaN,NaN,119971.650000,NaN,-3.896086e+06,NaN,NaN

In [37]:
df.isnull().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

## Data Type Management

In [38]:
df['Age'] = df['Age'].astype('float')
df['Salary'] = df['Salary'].astype('float')

## Date conversion

In [39]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')

## Chain cleaning

In [40]:
df['Department_Region'] = df['Department_Region'].str.strip().str.lower()
df['First_Name'] = df['First_Name'].str.strip().str.title()
df['Last_Name'] = df['Last_Name'].str.strip().str.upper()

df['Full_name'] = df['First_Name'] + " " + df['Last_Name']

## Handling missing values

In [41]:
df = df.dropna()

## Removing duplicates

In [42]:
df = df.drop_duplicates()

## Final Audit

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 787 entries, 0 to 1019
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        787 non-null    object
 1   First_Name         787 non-null    object
 2   Last_Name          787 non-null    object
 3   Age                787 non-null    float64
 4   Department_Region  787 non-null    object
 5   Status             787 non-null    object
 6   Join_Date          787 non-null    datetime64[ns]
 7   Salary             787 non-null    float64
 8   Email              787 non-null    object
 9   Phone              787 non-null    int64
 10  Performance_Score  787 non-null    object
 11  Remote_Work        787 non-null    bool
 12  Full_name          787 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 80.7+ KB

In [44]:
df.isnull().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
Full_name            0
dtype: int64

In [45]:
df.describe()

              Age                      Join_Date         Salary         Phone
count  787.000000                            787     787.000000  7.870000e+02
mean    32.471410  2022-08-06 07:22:47.725540096   85038.244536 -4.983687e+09
min     25.000000            2020-01-01 00:00:00   50047.320000 -9.994973e+09
25%     25.000000            2021-05-13 00:00:00   68074.625000 -7.343550e+09
50%     30.000000            2022-08-18 00:00:00   84972.700000 -5.034469e+09
75%     40.000000            2023-11-03 12:00:00  101419.855000 -2.632502e+09
max     40.000000            2024-12-29 00:00:00  119764.200000 -3.896086e+06
std      5.653042                            NaN   20014.968128  2.810127e+09

## Export

In [46]:
df.to_csv('cleaned_data.csv', index=False)